import type { FrameStyle } from "@machine-violet/shared/types/tui.js";

/** All shipped frame styles */
export const STYLES: FrameStyle[] = [
  {
    name: "gothic",
    genre_tags: ["grimdark", "horror", "dark_fantasy"],
    variants: {
      exploration: {
        horizontal: "═",
        vertical: "║",
        corner_tl: "╔",
        corner_tr: "╗",
        corner_bl: "╚",
        corner_br: "╝",
        flourish: "╡ %s ╞",
        color: "#888888",
      },
      combat: {
        horizontal: "━",
        vertical: "┃",
        corner_tl: "┏",
        corner_tr: "┓",
        corner_bl: "┗",
        corner_br: "┛",
        flourish: "┫ %s ┣",
        color: "#cc4444",
      },
      ooc: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "┤ %s ├",
        color: "#6688cc",
      },
      levelup: {
        horizontal: "═",
        vertical: "║",
        corner_tl: "╔",
        corner_tr: "╗",
        corner_bl: "╚",
        corner_br: "╝",
        flourish: "╡ ✦ %s ✦ ╞",
        color: "#ccaa44",
      },
      dev: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "┤ %s ├",
        color: "#33aa33",
      },
    },
  },
  {
    name: "arcane",
    genre_tags: ["high_fantasy", "epic"],
    variants: {
      exploration: {
        horizontal: "═",
        vertical: "║",
        corner_tl: "╔",
        corner_tr: "╗",
        corner_bl: "╚",
        corner_br: "╝",
        flourish: "═╡ ✧ %s ✧ ╞═",
        color: "#aa8844",
      },
      combat: {
        horizontal: "━",
        vertical: "┃",
        corner_tl: "┏",
        corner_tr: "┓",
        corner_bl: "┗",
        corner_br: "┛",
        flourish: "━┫ ⚔ %s ⚔ ┣━",
        color: "#cc2222",
      },
      ooc: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─┤ %s ├─",
        color: "#6688cc",
      },
      levelup: {
        horizontal: "═",
        vertical: "║",
        corner_tl: "╔",
        corner_tr: "╗",
        corner_bl: "╚",
        corner_br: "╝",
        flourish: "═╡ ★ %s ★ ╞═",
        color: "#eebb33",
      },
      dev: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─┤ %s ├─",
        color: "#33aa33",
      },
    },
  },
  {
    name: "terminal",
    genre_tags: ["sci-fi", "cyberpunk"],
    variants: {
      exploration: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─┤ %s ├─",
        color: "#33cc33",
      },
      combat: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─┤ >> %s << ├─",
        color: "#cc3333",
      },
      ooc: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─┤ %s ├─",
        color: "#cccc33",
      },
      levelup: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─┤ [+] %s [+] ├─",
        color: "#33cccc",
      },
      dev: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─┤ %s ├─",
        color: "#33aa33",
      },
    },
  },
  {
    name: "rustic",
    genre_tags: ["pastoral", "western", "low_fantasy"],
    variants: {
      exploration: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "╭",
        corner_tr: "╮",
        corner_bl: "╰",
        corner_br: "╯",
        flourish: "─┤ %s ├─",
        color: "#aa7744",
      },
      combat: {
        horizontal: "━",
        vertical: "┃",
        corner_tl: "┏",
        corner_tr: "┓",
        corner_bl: "┗",
        corner_br: "┛",
        flourish: "━┫ %s ┣━",
        color: "#cc6633",
      },
      ooc: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "╭",
        corner_tr: "╮",
        corner_bl: "╰",
        corner_br: "╯",
        flourish: "─┤ %s ├─",
        color: "#6688aa",
      },
      levelup: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "╭",
        corner_tr: "╮",
        corner_bl: "╰",
        corner_br: "╯",
        flourish: "─┤ ~ %s ~ ├─",
        color: "#ccaa44",
      },
      dev: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "╭",
        corner_tr: "╮",
        corner_bl: "╰",
        corner_br: "╯",
        flourish: "─┤ %s ├─",
        color: "#33aa33",
      },
    },
  },
  {
    name: "clean",
    genre_tags: ["modern", "freeform"],
    variants: {
      exploration: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─ %s ─",
      },
      combat: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─ %s ─",
        color: "#cc4444",
      },
      ooc: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─ %s ─",
        color: "#6688cc",
      },
      levelup: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─ * %s * ─",
        color: "#ccaa44",
      },
      dev: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─ %s ─",
        color: "#33aa33",
      },
    },
  },
  {
    name: "ornate",
    genre_tags: ["courtly", "mystery", "intrigue"],
    variants: {
      exploration: {
        horizontal: "═",
        vertical: "║",
        corner_tl: "╔",
        corner_tr: "╗",
        corner_bl: "╚",
        corner_br: "╝",
        flourish: "═╡ ❧ %s ❧ ╞═",
        color: "#9966aa",
      },
      combat: {
        horizontal: "━",
        vertical: "┃",
        corner_tl: "┏",
        corner_tr: "┓",
        corner_bl: "┗",
        corner_br: "┛",
        flourish: "━┫ ⚔ %s ⚔ ┣━",
        color: "#cc3333",
      },
      ooc: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─┤ %s ├─",
        color: "#6688cc",
      },
      levelup: {
        horizontal: "═",
        vertical: "║",
        corner_tl: "╔",
        corner_tr: "╗",
        corner_bl: "╚",
        corner_br: "╝",
        flourish: "═╡ ♛ %s ♛ ╞═",
        color: "#eebb33",
      },
      dev: {
        horizontal: "─",
        vertical: "│",
        corner_tl: "┌",
        corner_tr: "┐",
        corner_bl: "└",
        corner_br: "┘",
        flourish: "─┤ %s ├─",
        color: "#33aa33",
      },
    },
  },
];

/** Look up a style by name */
export function getStyle(name: string): FrameStyle | undefined {
  return STYLES.find((s) => s.name === name);
}

/** Find the best style for a genre tag */
export function styleForGenre(genre: string): FrameStyle {
  const tag = genre.toLowerCase().replace(/\s+/g, "_");
  const match = STYLES.find((s) => s.genre_tags.includes(tag));
  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion -- "clean" always exists in STYLES
  return match ?? STYLES.find((s) => s.name === "clean")!;
}
