/**
 * Generate the human-facing catalog docs from the shipped assets:
 *
 *   docs/campaign-seeds.md    ← worlds/*.mvworld
 *   docs/dm-personalities.md  ← personalities/*.mvdm
 *
 * Both docs are DERIVED — never hand-edit them. Regenerate after adding,
 * editing, or disabling a seed or personality:
 *
 *   npm run catalog:docs             # rewrite the two docs
 *   npm run catalog:docs -- --check  # verify up-to-date; exit 1 if stale (CI/hook)
 *
 * "Enabled" = the file is present without a `.disabled` suffix — disabling a
 * seed or voice is a filename rename, so the plain `.mvworld` / `.mvdm` filter
 * already excludes them.
 *
 * Only PLAYER-FACING content is emitted:
 *   - seeds: name, genres, summary/description, and `chooser: "player"` forks.
 *     Agent-chooser forks are DM-only setup secrets and are omitted, as is every
 *     AI-only field (`detail`, fork option `detail`, `setup_detail`).
 *   - personalities: name + description. The AI-only `prompt_fragment` / `detail`
 *     never appear.
 *
 * Self-contained by design (no engine/shared imports) so a PR hook can run it
 * without a build step. It mirrors the engine's fork handling: player forks are
 * `chooser: "player"`; legacy `suboptions` groups are player-facing too and are
 * appended after the explicit forks (matching `normalizeForks` in
 * packages/engine/src/config/world-forks.ts).
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));

interface ForkOption { name: string; description: string }
interface Fork { label: string; chooser?: "player" | "agent"; options: ForkOption[] }
interface Suboption { label: string; choices: ForkOption[] }
interface Seed {
  name: string;
  summary?: string;
  description?: string;
  genres?: string[];
  forks?: Fork[];
  suboptions?: Suboption[];
}

/** Player-facing forks only: `chooser: "player"` forks, then folded legacy suboptions. */
function playerForks(w: Seed): Array<{ label: string; options: ForkOption[] }> {
  const explicit = (w.forks ?? []).filter((f) => f.chooser === "player");
  const legacy = (w.suboptions ?? []).map((s) => ({ label: s.label, options: s.choices }));
  return [...explicit, ...legacy];
}

const detectEol = (raw: string): "\r\n" | "\n" => (raw.includes("\r\n") ? "\r\n" : "\n");
const byName = (a: { name: string }, b: { name: string }): number =>
  a.name.toLowerCase().localeCompare(b.name.toLowerCase());

/** Read a flat asset directory, keeping only files with `ext` (excludes `*.disabled`). */
function readAssets(dir: string, ext: string): unknown[] {
  const path = join(repoRoot, dir);
  if (!existsSync(path)) return [];
  return readdirSync(path)
    .filter((f) => f.endsWith(ext))
    .map((f) => JSON.parse(readFileSync(join(path, f), "utf8")) as unknown);
}

const GENERATED_BANNER =
  "<!-- GENERATED by scripts/gen-catalog-docs.ts — do not edit by hand. Run: npm run catalog:docs -->";

function renderSeeds(): string {
  const seeds = (readAssets("worlds", ".mvworld") as Seed[]).sort(byName);
  const out: string[] = [
    GENERATED_BANNER,
    "",
    "# Built-In Stories (Campaigns) Reference",
    "",
  ];

  for (const w of seeds) {
    out.push(`## ${w.name}`, "");
    if (w.genres?.length) out.push(`_${w.genres.join(", ")}_`, "");
    if (w.summary) out.push(w.summary, "");
    if (w.description) out.push(w.description, "");

    // Fold the setup choices into a collapsed <details> so the catalog stays
    // skimmable. The heading/genres/summary stay OUTSIDE it, so GitHub keeps the
    // per-seed anchor (campaign-seeds.md#the-shattered-crown) and TOC entry. The
    // blank line after <summary> and before </details> is required for GitHub to
    // render the Markdown inside.
    const forks = playerForks(w);
    if (forks.length) {
      out.push("<details><summary>Setup choices</summary>", "");
      for (const fork of forks) {
        out.push(`**${fork.label}**`, "");
        for (const o of fork.options) out.push(`- **${o.name}** — ${o.description}`);
        out.push("");
      }
      out.push("</details>", "");
    }
  }
  return finalize(out);
}

function renderPersonalities(): string {
  interface DMFile { name: string; description?: string }
  const voices = (readAssets("personalities", ".mvdm") as DMFile[]).sort(byName);
  const out: string[] = [
    GENERATED_BANNER,
    "",
    "# DM Personalities",
    "",
  ];

  for (const v of voices) {
    out.push(`## ${v.name}`, "");
    if (v.description) out.push(v.description, "");
  }
  return finalize(out);
}

/** Join lines, collapse trailing blanks to a single terminating newline. */
function finalize(lines: string[]): string {
  return lines.join("\n").replace(/\n+$/, "") + "\n";
}

/**
 * Write `content` to `path`, matching the file's existing EOL (LF for new files).
 * Returns true if the on-disk bytes changed (or in `check` mode, would change).
 */
function sync(relPath: string, content: string, check: boolean): boolean {
  const abs = join(repoRoot, relPath);
  const existing = existsSync(abs) ? readFileSync(abs, "utf8") : null;
  const eol = detectEol(existing ?? "\n");
  const out = eol === "\r\n" ? content.replace(/\n/g, "\r\n") : content;
  const changed = existing !== out;
  if (changed && !check) writeFileSync(abs, out);
  return changed;
}

function main(): void {
  const check = process.argv.slice(2).includes("--check");
  const targets: Array<[string, string]> = [
    ["docs/campaign-seeds.md", renderSeeds()],
    ["docs/dm-personalities.md", renderPersonalities()],
  ];

  const stale = targets.filter(([path, content]) => sync(path, content, check)).map(([p]) => p);

  if (check) {
    if (stale.length) {
      console.error(`Catalog docs are stale:\n  ${stale.join("\n  ")}\nRun: npm run catalog:docs`);
      process.exit(1);
    }
    console.log("Catalog docs are up to date.");
    return;
  }

  console.log(stale.length ? `Regenerated:\n  ${stale.join("\n  ")}` : "Catalog docs already current — nothing written.");
}

main();
